name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql-service:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: techlab_db
        ports:
          - 33306:3306
    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Execute tests
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: techlab_db
        DB_PORT: 33306
        DB_USER: root
        DB_PASSWORD: secret
      run: |
        php artisan migrate
        vendor/bin/phpunit
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
